services:

  # This service is optional, I just like having an interface to see the DB
  adminer:
    image: adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "portmapping:portmapping" # <- to be replaced

  db:
    image: mysql:9.7
    restart: always
    environment:
      MYSQL_USER: "YOUR_SQL_USER" # <- to be replaced
      MYSQL_ROOT_PASSWORD: "YOUR_SQL_ROOT_PASSWORD" # <- to be replaced
      MYSQL_PASSWORD: "YOUR_SQL_USER_PASSWORD" # <- to be replaced
      MYSQL_DATABASE: "YOUR_SQL_DB_NAME" # <- to be replaced
    ports:
      - "portmapping:portmapping" # <- to be replaced
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    restart: always
    depends_on:
      db:
        condition: service_healthy
    build: .
    env_file:
      - .env
    ports:
      - "portmapping:portmapping" # <- to be replaced
    # API needs this to look up local files, make sure this is the same as in .env
    volumes:
      - type: bind
        source: "/your/path/to/local/mp3s" # <- to be replaced
        target: "/your/path/to/local/mp3s" # <- to be replaced
        read_only: true

volumes:
  db_data: